version: "2.1"
services:  
  # test container
  test:
    build:
      context: .
      dockerfile: ./testutil/Dockerfile
    environment:
      AWS_ACCESS_KEY_ID: xxxxx
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: xxxxx
      AWS_SESSION_TOKEN: xxxxx
      KINESIS_ENDPOINT: http://kinesis:4567
      S3_ENDPOINT: http://s3:8000
    links:
      - kinesis:kinesis
      - s3:s3
    volumes:
      - ./:/go/src/s3-kinesis-replay
      - ./testutil/config.yml:/etc/s3-kinesis-replay/config.yml
      - ./testutil/schema.json:/etc/s3-kinesis-replay/schema.json
      - /go/src/s3-kinesis-replay/vendor
      - /go/src/s3-kinesis-replay/.gopath~
  
  # kinesis container
  kinesis:
    image: vsouza/kinesis-local
    command: --port 4567 --shardLimit 100
    ports:
      - "4567:4567"

  # s3 container
  s3:
    image: scality/s3server
    ports:
     - "8000:8000"